Algoritmo "eleitores"

Var
totalEleitores: inteiro
totalBrancos: inteiro
totalNulos: inteiro
totalValidos: inteiro
votos: inteiro
percentual: real

//Mostrar percentual de votos
procedimento mostrarPercentual()
   Inicio
      escreval("Digite o total de eleitores")
      leia(totalEleitores)
      escreval ("Digite o total de votos em branco")
      leia (votos)


      

fimProcedimento

Inicio
mostrarPercentual()






Fimalgoritmo